"""Change Table Name from Config to Setup

Revision ID: 07618534783e
Revises: 276d23f4423c
Create Date: 2025-01-21 22:40:14.765076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07618534783e'
down_revision = '276d23f4423c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###
