"""Add color_hex field to Classes

Revision ID: 204edc11db81
Revises: 24ff9fdb101d
Create Date: 2025-01-19 07:43:01.549202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204edc11db81'
down_revision = '24ff9fdb101d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_hex', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('color_hex')

    # ### end Alembic commands ###
