"""Drop class_type field from Attendances

Revision ID: 5eab75acdbe8
Revises: 07618534783e
Create Date: 2025-01-23 14:23:20.176648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eab75acdbe8'
down_revision = '07618534783e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('class_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_type', sa.VARCHAR(length=10), server_default=sa.text("'extra'"), nullable=False))

    # ### end Alembic commands ###
