"""Created_by added to Attendance Table

Revision ID: 68391865a24e
Revises: c8b4f73c03d1
Create Date: 2025-02-19 05:51:32.724087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68391865a24e'
down_revision = 'c8b4f73c03d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
