"""Agregar organization_id a la tabla Classes

Revision ID: 8ec70d3164ce
Revises: 68391865a24e
Create Date: 2025-02-20 19:48:45.999832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec70d3164ce'
down_revision = '68391865a24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_classes')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')

    op.create_table('_alembic_tmp_classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('class_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('class_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('schedule', sa.VARCHAR(length=10), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('class_color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('meeting_center_id', sa.INTEGER(), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['meeting_center_id'], ['meeting_center.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='fk_classes_organization_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_code', 'meeting_center_id', name='uq_class_code_meeting_center'),
    sa.UniqueConstraint('class_name', 'meeting_center_id', name='uq_class_name_meeting_center'),
    sa.UniqueConstraint('short_name', 'meeting_center_id', name='uq_short_name_meeting_center')
    )
    # ### end Alembic commands ###
