"""Add class_type to Attendance with default value

Revision ID: 7bb2f8f653c2
Revises: a2929241ea48
Create Date: 2025-01-18 23:58:23.476926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb2f8f653c2'
down_revision = 'a2929241ea48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_type', sa.String(length=10), nullable=False, server_default='extra'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('class_type')

    # ### end Alembic commands ###
