"""Add class_type to Classes with default value

Revision ID: a2929241ea48
Revises: ac36539f666f
Create Date: 2025-01-18 23:54:41.814539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2929241ea48'
down_revision = 'ac36539f666f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_type', sa.String(length=10), nullable=False, server_default='extra'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('class_type')

    # ### end Alembic commands ###
